# Generated by Django 4.2 on 2023-04-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='picture',
            new_name='image',
        ),
    ]
