# Generated by Django 4.2 on 2023-05-06 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_duration_alter_auction_buy_now_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
