# Generated by Django 4.2 on 2023-05-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_date_opinion_date_created_opinion_date_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
