# Generated by Django 4.2 on 2023-05-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('expired', 'expired')], default='available', max_length=64),
        ),
    ]
