# Generated by Django 4.2 on 2023-05-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('expired', 'expired'), ('sold', 'sold')], default='available', max_length=64),
        ),
    ]
