# Generated by Django 4.2 on 2023-05-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_account_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='birthday',
        ),
    ]
