# Generated by Django 4.2 on 2023-05-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='images/', width_field=200),
        ),
    ]
