# Generated by Django 4.2 on 2023-05-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_item_height_field_item_width_field_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
