# Generated by Django 4.2 on 2023-05-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_item_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='date_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
