# Generated by Django 4.0.2 on 2023-06-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_opinion_date_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.SlugField(max_length=64),
        ),
    ]
