# Generated by Django 4.0.2 on 2023-06-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_opinion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
